### ISSUE TITLE
im also making a client, can we merge clients and both work on it?

### ISSUE THREAD

**Issue by AstroOrbis** [DentClient/Client#4]

**Comment by Whop42** [comment]
your client is based on meteor

**Comment by Whop42** [comment]
no

**Comment by AstroOrbis** [comment]
no im not basing it on meteor anymore I'm doing it from FoxBase, which is what you also use

**Comment by Whop42** [comment]
i use an old version of foxbase from before cf4m

**Comment by Whop42** [comment]
you can contribute to this though

**Comment by AstroOrbis** [comment]
nice pog
